services:
  web:
    build: .
    command: sh -c "python manage.py wait_for_database && python manage.py makemigrations && python manage.py migrate && python manage.py load_data && gunicorn credit_system.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=credit_system.settings

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A credit_system worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=credit_system.settings

volumes:
  pgdata:
